coba

diff --git a/.github/workflows/mlflow-ci.yml b/.github/workflows/mlflow-ci.yml
--- a/.github/workflows/mlflow-ci.yml
+++ b/.github/workflows/mlflow-ci.yml
@@ -83,13 +83,16 @@ jobs:
       - name: Get latest MLflow run id
         id: get_run
         run: |
-          RUN_ID=$(mlflow runs list \
-          --experiment-name hr-attrition-ci \
-          --max-results 1 \
-          --output json | jq -r '.[0].run_id')
+          RUN_ID=$(mlflow runs list --max-results 1 --output json | jq -r '.[0].run_id')
+
+          if [ -z "$RUN_ID" ] || [ "$RUN_ID" = "null" ]; then
+            echo "ERROR: RUN_ID kosong"
+            exit 1
+          fi
 
           echo "RUN_ID=$RUN_ID"
           echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
+
 
 
       # =========================
